a = int(input('Введите число '))
b = int(input('Введите число '))
print('a=', a)
print('b=', b)
print('a+b=',a+b)
print('a*b=',a*b)
print('a-b=',a-b)
print('a/b=',a/b)
print('a^b=',a**b)
print('a mod b=',a%b)
print('a div b=',a//b)
print('-a, -b=',-a ,-b)
print('sqr(a)=',a**2)
print('a in bin',bin(a))
print('a in oct',oct(a))
print('a in hex',hex(a))
